name: Internexio LLC
favicon: null
layout_spectrum: 0.47496
typography_spectrum: 0.24457
title: Seattle Paid Search Marketing Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1527532-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3cbbfc'
    - '#00549b'
    - '#00ffff'
    - '#0000ff'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
